### PR TITLE
Adds support for a Docker-based Microkernel to Hanlon

### PR DESCRIPTION
**Pull request by tjmcs**
Modifies the Hanlon-Microkernel project so that it includes a Dockerfile that can be used to build a Docker image containing the Hanlon Microkernel bits (instead of building a custom TinyCore Linux ISO that contains these same bits).  This image must then be saved/exported into a tarfile that can be used as part of the "hanlon image add ..." command (along with a RancherOS ISO) to add a new Microkernel to Hanlon.

### CODE REVIEW

**Comment by tjmcs** [comment]
this pull request must be merged at the same time that PR 404 in the Hanlon project is merged since it's a breaking change to the Hanlon APIs (and CLI).

**Comment by jcpowermac** [comment]
@tjmcs after the documentation update I am good with this PR.

See testing https://github.com/csc/Hanlon/pull/404

**Comment by jcpowermac** [comment]
Documentation looks good :+1:

**Comment by mtnbikenc** [comment]
Tested locally in a VM and code review with @tjmcs :+1: to merge

**Pull request merged**
